import { type Shader, ShaderColor } from "./types";

const DB: Shader[] = [
    {
        name: "Always North",
        source: "Source: Forsaken Annual Pass",
        image: "/common/destiny2_content/icons/80699ae7fd7f109f2d0521b07eb0db35.jpg",
        colors: {
            TopFabric: ShaderColor.Red,
            LeftFabric: ShaderColor.Yellow,
            RightFabric: ShaderColor.Green,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Orange,
            InnerMetal: ShaderColor.Green,
        },
    },
    {
        name: "Diametric Crush",
        source: "Source: \"Salvation's Edge\" Raid",
        image: "/common/destiny2_content/icons/5c2102e7dd7068c38059b518038af413.jpg",
        colors: {
            TopFabric: ShaderColor.White,
            LeftFabric: ShaderColor.White,
            RightFabric: ShaderColor.Black,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.Yellow,
            BottomLight: ShaderColor.Yellow,
            OuterMetal: ShaderColor.White,
            InnerMetal: ShaderColor.Green,
        },
    },
    {
        name: "Superblack",
        source: "Source: Season of the Wish",
        image: "/common/destiny2_content/icons/574f5c8ef1eea552d2f2e01c6141a465.jpg",
        colors: {
            TopFabric: ShaderColor.Black,
            LeftFabric: ShaderColor.Black,
            RightFabric: ShaderColor.Black,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Black,
            InnerMetal: ShaderColor.Black,
        },
    },
    {
        name: "Ablaze",
        source: "Source: Eververse",
        image: "/common/destiny2_content/icons/403f3cae7ac06b46ef11fc5792291179.jpg",
        colors: {
            TopFabric: ShaderColor.NoColor,
            LeftFabric: ShaderColor.Black,
            RightFabric: ShaderColor.Red,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.Yellow,
            BottomLight: ShaderColor.Yellow,
            OuterMetal: ShaderColor.Yellow,
            InnerMetal: ShaderColor.Blue,
        },
    },
    {
        name: "(Adroit)",
        source: "",
        image: "/common/destiny2_content/icons/06b08aa4ec68cededb448acb36646f5a.jpg",
        colors: {
            TopFabric: ShaderColor.Blue,
            LeftFabric: ShaderColor.Black,
            RightFabric: ShaderColor.Grey,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.Red,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Black,
            InnerMetal: ShaderColor.Grey,
        },
    },
    {
        name: "3 Connections",
        source: "Source: Unlocked by a special offer",
        image: "/common/destiny2_content/icons/ea56ddae449a596f2c60e6abe7b563ca.jpg",
        colors: {
            TopFabric: ShaderColor.Blue,
            LeftFabric: ShaderColor.Black,
            RightFabric: ShaderColor.White,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.Pink,
            BottomLight: ShaderColor.Pink,
            OuterMetal: ShaderColor.Pink,
            InnerMetal: ShaderColor.Blue,
        },
    },
    {
        name: "Abyssinian Gold",
        source: "Source: Eververse",
        image: "/common/destiny2_content/icons/0960967cc56da702e4757af9dfa0c88c.jpg",
        colors: {
            TopFabric: ShaderColor.Black,
            LeftFabric: ShaderColor.Grey,
            RightFabric: ShaderColor.Black,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.Red,
            BottomLight: ShaderColor.Red,
            OuterMetal: ShaderColor.Grey,
            InnerMetal: ShaderColor.Yellow,
        },
    },
    {
        name: "Aces Full of Kings",
        source: "Source: Eververse",
        image: "/common/destiny2_content/icons/35d1ea3988645dff04da9e2c1a9c6d3c.jpg",
        colors: {
            TopFabric: ShaderColor.Yellow,
            LeftFabric: ShaderColor.Red,
            RightFabric: ShaderColor.Black,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.Blue,
            BottomLight: ShaderColor.Orange,
            OuterMetal: ShaderColor.Blue,
            InnerMetal: ShaderColor.Yellow,
        },
    },
    {
        name: "Amaranth Atrocity",
        source: "Source: Festival of the Lost 2018",
        image: "/common/destiny2_content/icons/5a649decca5fde3ac4d5cd001b583e19.jpg",
        colors: {
            TopFabric: ShaderColor.White,
            LeftFabric: ShaderColor.Black,
            RightFabric: ShaderColor.Blue,
            BottomFabric: ShaderColor.White,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Purple,
            InnerMetal: ShaderColor.Pink,
        },
    },
    {
        name: "Alchemy Scorch",
        source: "Source: Festival of the Lost 2020",
        image: "/common/destiny2_content/icons/987e90cb544fda80dbbf9a9e16e28835.jpg",
        colors: {
            TopFabric: ShaderColor.Black,
            LeftFabric: ShaderColor.Black,
            RightFabric: ShaderColor.Blue,
            BottomFabric: ShaderColor.Brown,
            TopLight: ShaderColor.Lime,
            BottomLight: ShaderColor.Lime,
            OuterMetal: ShaderColor.Cyan,
            InnerMetal: ShaderColor.Grey,
        },
    },
    
]

export default DB;
