import { type Shader, ShaderColor } from "./types";

const DB: Shader[] = [
    {
        name: "Always North",
        source: "Source: Forsaken Annual Pass",
        image: "/common/destiny2_content/icons/80699ae7fd7f109f2d0521b07eb0db35.jpg",
        colors: {
            TopFabric: ShaderColor.Red,
            LeftFabric: ShaderColor.Yellow,
            RightFabric: ShaderColor.Green,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Orange,
            InnerMetal: ShaderColor.Green,
        },
    },
    {
        name: "Diametric Crush",
        source: "Source: \"Salvation's Edge\" Raid",
        image: "/common/destiny2_content/icons/5c2102e7dd7068c38059b518038af413.jpg",
        colors: {
            TopFabric: ShaderColor.White,
            LeftFabric: ShaderColor.White,
            RightFabric: ShaderColor.Black,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.Yellow,
            BottomLight: ShaderColor.Yellow,
            OuterMetal: ShaderColor.White,
            InnerMetal: ShaderColor.Green,
        },
    },
    {
        name: "Superblack",
        source: "Source: Season of the Wish",
        image: "/common/destiny2_content/icons/574f5c8ef1eea552d2f2e01c6141a465.jpg",
        colors: {
            TopFabric: ShaderColor.Black,
            LeftFabric: ShaderColor.Black,
            RightFabric: ShaderColor.Black,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Black,
            InnerMetal: ShaderColor.Black,
        },
    },
    {
        name: "Ablaze",
        source: "Source: Eververse",
        image: "/common/destiny2_content/icons/403f3cae7ac06b46ef11fc5792291179.jpg",
        colors: {
            TopFabric: ShaderColor.Brown,
            LeftFabric: ShaderColor.Black,
            RightFabric: ShaderColor.Red,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.Yellow,
            BottomLight: ShaderColor.Yellow,
            OuterMetal: ShaderColor.Yellow,
            InnerMetal: ShaderColor.Blue,
        },
    },
    {
        name: "(Adroit)",
        source: "",
        image: "/common/destiny2_content/icons/06b08aa4ec68cededb448acb36646f5a.jpg",
        colors: {
            TopFabric: ShaderColor.Blue,
            LeftFabric: ShaderColor.Black,
            RightFabric: ShaderColor.Grey,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.Red,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Black,
            InnerMetal: ShaderColor.Grey,
        },
    },
    {
        name: "3 Connections",
        source: "Source: Unlocked by a special offer",
        image: "/common/destiny2_content/icons/ea56ddae449a596f2c60e6abe7b563ca.jpg",
        colors: {
            TopFabric: ShaderColor.Blue,
            LeftFabric: ShaderColor.Black,
            RightFabric: ShaderColor.White,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.Pink,
            BottomLight: ShaderColor.Pink,
            OuterMetal: ShaderColor.Pink,
            InnerMetal: ShaderColor.Blue,
        },
    },
    {
        name: "Abyssinian Gold",
        source: "Source: Eververse",
        image: "/common/destiny2_content/icons/0960967cc56da702e4757af9dfa0c88c.jpg",
        colors: {
            TopFabric: ShaderColor.Black,
            LeftFabric: ShaderColor.Grey,
            RightFabric: ShaderColor.Black,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.Red,
            BottomLight: ShaderColor.Red,
            OuterMetal: ShaderColor.Grey,
            InnerMetal: ShaderColor.Yellow,
        },
    },
    {
        name: "Aces Full of Kings",
        source: "Source: Eververse",
        image: "/common/destiny2_content/icons/35d1ea3988645dff04da9e2c1a9c6d3c.jpg",
        colors: {
            TopFabric: ShaderColor.Yellow,
            LeftFabric: ShaderColor.Red,
            RightFabric: ShaderColor.Black,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.Blue,
            BottomLight: ShaderColor.Orange,
            OuterMetal: ShaderColor.Blue,
            InnerMetal: ShaderColor.Yellow,
        },
    },
    {
        name: "Amaranth Atrocity",
        source: "Source: Festival of the Lost 2018",
        image: "/common/destiny2_content/icons/5a649decca5fde3ac4d5cd001b583e19.jpg",
        colors: {
            TopFabric: ShaderColor.White,
            LeftFabric: ShaderColor.Black,
            RightFabric: ShaderColor.Blue,
            BottomFabric: ShaderColor.White,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Purple,
            InnerMetal: ShaderColor.Pink,
        },
    },
    {
        name: "Alchemy Scorch",
        source: "Source: Festival of the Lost 2020",
        image: "/common/destiny2_content/icons/987e90cb544fda80dbbf9a9e16e28835.jpg",
        colors: {
            TopFabric: ShaderColor.Black,
            LeftFabric: ShaderColor.Black,
            RightFabric: ShaderColor.Blue,
            BottomFabric: ShaderColor.Brown,
            TopLight: ShaderColor.Lime,
            BottomLight: ShaderColor.Lime,
            OuterMetal: ShaderColor.Cyan,
            InnerMetal: ShaderColor.Grey,
        },
    },
    {
        name: "Amethyst Bloom",
        source: "Source: Eververse",
        image: "/common/destiny2_content/icons/5f4e2c1c0fc4b15f62fb2fb7402e545e.jpg",
        colors: {
            TopFabric: ShaderColor.Blue,
            LeftFabric: ShaderColor.Grey,
            RightFabric: ShaderColor.White,
            BottomFabric: ShaderColor.Brown,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.Blue,
            OuterMetal: ShaderColor.Pink,
            InnerMetal: ShaderColor.Purple,
        },
    },
    {
        name: "Amethyst Veil",
        source: "Source: Eververse",
        image: "/common/destiny2_content/icons/bdb2fb17627a928461d17a24f7844bc9.jpg",
        colors: {
            TopFabric: ShaderColor.Black,
            LeftFabric: ShaderColor.White,
            RightFabric: ShaderColor.Black,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.Purple,
            BottomLight: ShaderColor.Purple,
            OuterMetal: ShaderColor.Grey,
            InnerMetal: ShaderColor.Black,
        },
    },
    {
        name: "Amrita's Dream",
        source: "Source: Season Pass Reward",
        image: "/common/destiny2_content/icons/d166600a3e731da441989d1db6b1c84f.jpg",
        colors: {
            TopFabric: ShaderColor.Purple,
            LeftFabric: ShaderColor.Black,
            RightFabric: ShaderColor.White,
            BottomFabric: ShaderColor.White,
            TopLight: ShaderColor.Lime,
            BottomLight: ShaderColor.Purple,
            OuterMetal: ShaderColor.Purple,
            InnerMetal: ShaderColor.Grey,
        },
    },
    {
        name: "Ancient Believer",
        source: "Source: \"Garden of Salvation\" Raid",
        image: "/common/destiny2_content/icons/5db4ed8238392e9fd336c91a19e38fbd.jpg",
        colors: {
            TopFabric: ShaderColor.White,
            LeftFabric: ShaderColor.Black,
            RightFabric: ShaderColor.Black,
            BottomFabric: ShaderColor.Brown,
            TopLight: ShaderColor.Red,
            BottomLight: ShaderColor.Red,
            OuterMetal: ShaderColor.Grey,
            InnerMetal: ShaderColor.Yellow,
        },
    },
    {
        name: "Ancient Defender",
        source: "Source: \"Garden of Salvation\" Raid",
        image: "/common/destiny2_content/icons/13818a382d7d452567477577aaa1927a.jpg",
        colors: {
            TopFabric: ShaderColor.Purple,
            LeftFabric: ShaderColor.Black,
            RightFabric: ShaderColor.Black,
            BottomFabric: ShaderColor.Brown,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Brown,
            InnerMetal: ShaderColor.Black,
        },
    },
    {
        name: "Ancient Republic",
        source: "Source: Bright Engrams",
        image: "/common/destiny2_content/icons/88411636d62b3510abcbd3f7dea8216e.jpg",
        colors: {
            TopFabric: ShaderColor.Red,
            LeftFabric: ShaderColor.White,
            RightFabric: ShaderColor.Black,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.White,
            InnerMetal: ShaderColor.Purple,
        },
    },
    {
        name: "Angel's Gleam",
        source: "Source: Upgraded Event Card Reward",
        image: "/common/destiny2_content/icons/8a86ad973e5769cb4b611bc0a6d8be3a.jpg",
        colors: {
            TopFabric: ShaderColor.Yellow,
            LeftFabric: ShaderColor.Grey,
            RightFabric: ShaderColor.Yellow,
            BottomFabric: ShaderColor.Blue,
            TopLight: ShaderColor.Red,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Red,
            InnerMetal: ShaderColor.White,
        },
    },
    {
        name: "Aniline Shock",
        source: "Source: Bright Engrams",
        image: "/common/destiny2_content/icons/0d85ed10a81cd39361ff2da2db041cc1.jpg",
        colors: {
            TopFabric: ShaderColor.White,
            LeftFabric: ShaderColor.Black,
            RightFabric: ShaderColor.Black,
            BottomFabric: ShaderColor.White,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.White,
            InnerMetal: ShaderColor.Blue,
        },
    },
    {
        name: "Anyone's Game",
        source: "Source: Season 13 Guardian Games",
        image: "/common/destiny2_content/icons/32e782f806987d5e8f6d57ca07015e4f.jpg",
        colors: {
            TopFabric: ShaderColor.Yellow,
            LeftFabric: ShaderColor.Blue,
            RightFabric: ShaderColor.White,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.Red,
            OuterMetal: ShaderColor.Red,
            InnerMetal: ShaderColor.White,
        },
    },
    {
        name: "Aposematism",
        source: "Source: Eververse",
        image: "/common/destiny2_content/icons/157eed2951ce8ad5cdf02564b94bedb6.jpg",
        colors: {
            TopFabric: ShaderColor.Grey,
            LeftFabric: ShaderColor.Orange,
            RightFabric: ShaderColor.Grey,
            BottomFabric: ShaderColor.Black,
            TopLight: ShaderColor.Orange,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Orange,
            InnerMetal: ShaderColor.Black,
        },
    },
    {
        name: "Aquatic Iridescence",
        source: "Source: Eververse",
        image: "/common/destiny2_content/icons/a299d62a967a9654307e286a71cb550e.jpg",
        colors: {
            TopFabric: ShaderColor.Grey,
            LeftFabric: ShaderColor.Orange,
            RightFabric: ShaderColor.Purple,
            BottomFabric: ShaderColor.Green,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Green,
            InnerMetal: ShaderColor.Purple,
        },
    },
    {
        name: "Arboreal Refuge",
        source: "Source: Upgraded Event Card Reward",
        image: "/common/destiny2_content/icons/0c9055a8bd272ea6cd336ad655660031.jpg",
        colors: {
            TopFabric: ShaderColor.Green,
            LeftFabric: ShaderColor.Orange,
            RightFabric: ShaderColor.Brown,
            BottomFabric: ShaderColor.Green,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Yellow,
            InnerMetal: ShaderColor.Green,
        },
    },
    {
        name: "Archeoskin",
        source: "Source: Eververse",
        image: "/common/destiny2_content/icons/1acc96e759717d4c29547ae03ffca3a0.jpg",
        colors: {
            TopFabric: ShaderColor.Grey,
            LeftFabric: ShaderColor.Yellow,
            RightFabric: ShaderColor.Grey,
            BottomFabric: ShaderColor.Green,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Yellow,
            InnerMetal: ShaderColor.Grey,
        },
    },
    {
        name: "Arctic Dreamscape",
        source: "Source: Ada-1",
        image: "/common/destiny2_content/icons/0bf8be7bfa8dd27d20d1e52bad6130b3.jpg",
        colors: {
            TopFabric: ShaderColor. White,
            LeftFabric: ShaderColor.Orange,
            RightFabric: ShaderColor.Blue,
            BottomFabric: ShaderColor.Grey,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Black,
            InnerMetal: ShaderColor.White,
        },
    },
    {
        name: "Arctic Pearl",
        source: "Source: Bright Engrams",
        image: "/common/destiny2_content/icons/05402e116c3d4a4d3daa3f9c26c5c6e8.jpg",
        colors: {
            TopFabric: ShaderColor.Grey,
            LeftFabric: ShaderColor.Grey,
            RightFabric: ShaderColor.White,
            BottomFabric: ShaderColor.Brown,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Brown,
            InnerMetal: ShaderColor.White,
        },
    },
    {
        name: "Argent Champion",
        source: "Source: Unlocked by a special offer.",
        image: "/common/destiny2_content/icons/268fa24bbebd7a50e84ff5acf8d0d80d.jpg",
        colors: {
            TopFabric: ShaderColor.Blue,
            LeftFabric: ShaderColor.Blue,
            RightFabric: ShaderColor.White,
            BottomFabric: ShaderColor.Purple,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Blue,
            InnerMetal: ShaderColor.Grey,
        },
    },
    {
        name: "Argent Teratorn",
        source: "Source: Eververse",
        image: "/common/destiny2_content/icons/bfac98853fe988cf1ca38f299e13ee4e.jpg",
        colors: {
            TopFabric: ShaderColor.Grey,
            LeftFabric: ShaderColor.Red,
            RightFabric: ShaderColor.Blue,
            BottomFabric: ShaderColor.Grey,
            TopLight: ShaderColor.Red,
            BottomLight: ShaderColor.Red,
            OuterMetal: ShaderColor.Pink,
            InnerMetal: ShaderColor.White,
        },
    },
    {
        name: "Armatura",
        source: "Source: Season Pass Reward",
        image: "/common/destiny2_content/icons/a32914ea30943e64c0cabbc35c720025.jpg",
        colors: {
            TopFabric: ShaderColor.Brown,
            LeftFabric: ShaderColor.Blue,
            RightFabric: ShaderColor.Blue,
            BottomFabric: ShaderColor.Brown,
            TopLight: ShaderColor.Yellow,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Yellow,
            InnerMetal: ShaderColor.Green,
        },
    },
    {
        name: "Atlantic Rush",
        source: "Source: Bright Engrams",
        image: "/common/destiny2_content/icons/04375e3419f70ae67dd1ab6d963f42fc.jpg",
        colors: {
            TopFabric: ShaderColor.Cyan,
            LeftFabric: ShaderColor.Red,
            RightFabric: ShaderColor.Blue,
            BottomFabric: ShaderColor.Blue,
            TopLight: ShaderColor.White,
            BottomLight: ShaderColor.White,
            OuterMetal: ShaderColor.Red,
            InnerMetal: ShaderColor.Cyan,
        },
    },
    
]

export default DB;
